name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - name: Maven cache
      uses: actions/cache@v1
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
        restore-keys: |
            ${{ runner.os }}-maven-
    - name: Install dependencies
      run: lein deps
    - name: Run codox
      run: lein codox
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
